In [1]:
db = "./census/census.db"

In [2]:
%load_ext sql
%config SqlMagic.feedback=False
%sql sqlite:///{db}?check_same_thread=false
%sql SELECT name FROM sqlite_master WHERE type='table';

 * sqlite:///./census/census.db?check_same_thread=false

[('census',)]

`$.schema`
```sql
CREATE TABLE IF NOT EXISTS "census" (
    "id" INTEGER,
    "district" TEXT NOT NULL,
    "locality" TEXT NOT NULL,
    "families" INTEGER NOT NULL,
    "households" INTEGER NOT NULL,
    "population" INTEGER NOT NULL,
    "male" INTEGER NOT NULL,
    "female" INTEGER NOT NULL,
    PRIMARY KEY("id")
);
```

In [9]:
%sql SELECT * FROM "census" LIMIT 20;

 * sqlite:///./census/census.db?check_same_thread=false

[(1, 'Taplejung', 'Aathrai Tribeni Rural Municipality', 2869, 2735, 12288, 6005, 6283),
 (2, 'Taplejung', 'Maiwakhola Rural Municipality', 2275, 2178, 10365, 5264, 5101),
 (3, 'Taplejung', 'Meringden Rural Municipality', 2683, 2528, 12040, 6181, 5859),
 (4, 'Taplejung', 'Mikwakhola Rural Municipality', 1862, 1792, 7991, 4000, 3991),
 (5, 'Taplejung', 'Phaktanglung Rural Municipality', 2864, 2700, 11925, 6239, 5686),
 (6, 'Taplejung', 'Phungling Municipality', 7306, 5888, 28786, 14160, 14626),
 (7, 'Taplejung', 'Sidingba Rural Municipality', 2604, 2484, 10981, 5593, 5388),
 (8, 'Taplejung', 'Sirijangha Rural Municipality', 3329, 3197, 14186, 7227, 6959),
 (9, 'Taplejung', 'Pathivara Yangwarak Rural Municipality', 2738, 2637, 11797, 5855, 5942),
 (10, 'Panchthar', 'Falelung Rural Municipality', 4940, 4773, 20531, 10211, 10320),
 (11, 'Panchthar', 'Falgunanda Rural Municipality', 5293, 4968, 21253, 10417, 10836),
 (12, 'Panchthar', 'Hilihang Rural Municipality', 4878, 4647, 20537, 10160, 10377),
 (13, 'Panchthar', 'Kummayak Rural Municipality', 3199, 3012, 13020, 6532, 6488),
 (14, 'Panchthar', 'Miklajung Rural Municipality', 5509, 5163, 21328, 10535, 10793),
 (15, 'Panchthar', 'Phidim Municipality', 12433, 10442, 48713, 23963, 24750),
 (16, 'Panchthar', 'Tumbewa Rural Municipality', 2752, 2636, 11063, 5644, 5419),
 (17, 'Panchthar', 'Yangwarak Rural Municipality', 3964, 3765, 16828, 8509, 8319),
 (18, 'Ilam', 'Chulachuli Rural Municipality', 5624, 5533, 22856, 11215, 11641),
 (19, 'Ilam', 'Deumai Municipality', 7907, 7535, 31531, 15807, 15724),
 (20, 'Ilam', 'Fakphokthum Rural Municipality', 4923, 4748, 20004, 9800, 10204)]

In [6]:
%%sql
CREATE VIEW "rural" AS
SELECT * FROM "census"
WHERE "locality" LIKE '%Rural%';

 * sqlite:///./census/census.db?check_same_thread=false

[]

In [12]:
%sql SELECT * FROM "rural" LIMIT 20;

 * sqlite:///./census/census.db?check_same_thread=false

[(1, 'Taplejung', 'Aathrai Tribeni Rural Municipality', 2869, 2735, 12288, 6005, 6283),
 (2, 'Taplejung', 'Maiwakhola Rural Municipality', 2275, 2178, 10365, 5264, 5101),
 (3, 'Taplejung', 'Meringden Rural Municipality', 2683, 2528, 12040, 6181, 5859),
 (4, 'Taplejung', 'Mikwakhola Rural Municipality', 1862, 1792, 7991, 4000, 3991),
 (5, 'Taplejung', 'Phaktanglung Rural Municipality', 2864, 2700, 11925, 6239, 5686),
 (7, 'Taplejung', 'Sidingba Rural Municipality', 2604, 2484, 10981, 5593, 5388),
 (8, 'Taplejung', 'Sirijangha Rural Municipality', 3329, 3197, 14186, 7227, 6959),
 (9, 'Taplejung', 'Pathivara Yangwarak Rural Municipality', 2738, 2637, 11797, 5855, 5942),
 (10, 'Panchthar', 'Falelung Rural Municipality', 4940, 4773, 20531, 10211, 10320),
 (11, 'Panchthar', 'Falgunanda Rural Municipality', 5293, 4968, 21253, 10417, 10836),
 (12, 'Panchthar', 'Hilihang Rural Municipality', 4878, 4647, 20537, 10160, 10377),
 (13, 'Panchthar', 'Kummayak Rural Municipality', 3199, 3012, 13020, 6532, 6488),
 (14, 'Panchthar', 'Miklajung Rural Municipality', 5509, 5163, 21328, 10535, 10793),
 (16, 'Panchthar', 'Tumbewa Rural Municipality', 2752, 2636, 11063, 5644, 5419),
 (17, 'Panchthar', 'Yangwarak Rural Municipality', 3964, 3765, 16828, 8509, 8319),
 (18, 'Ilam', 'Chulachuli Rural Municipality', 5624, 5533, 22856, 11215, 11641),
 (20, 'Ilam', 'Fakphokthum Rural Municipality', 4923, 4748, 20004, 9800, 10204),
 (22, 'Ilam', 'Maijogmai Rural Municipality', 4957, 4881, 19295, 9686, 9609),
 (24, 'Ilam', 'Mangsebung Rural Municipality', 3891, 3793, 16897, 8602, 8295),
 (25, 'Ilam', 'Rong Rural Municipality', 4715, 4650, 17555, 8739, 8816)]

In [16]:
%%sql
CREATE VIEW "total" AS
SELECT
    SUM("families") AS "families",
    SUM("households") AS "households",
    SUM("population") AS "population",
    SUM("male") AS "male",
    SUM("female") AS "female"
FROM "census";

 * sqlite:///./census/census.db?check_same_thread=false

[]

In [17]:
%sql SELECT * FROM "total";

 * sqlite:///./census/census.db?check_same_thread=false

[(6759473, 5642674, 29074990, 14188639, 14886351)]

In [19]:
%%sql
CREATE VIEW "by_district" AS
SELECT
    "district",
    SUM("families") AS "families",
    SUM("households") AS "households",
    SUM("population") AS "population",
    SUM("male") AS "male",
    SUM("female") AS "female"
FROM "census"
GROUP BY "district";

 * sqlite:///./census/census.db?check_same_thread=false

[]

In [21]:
%sql SELECT * FROM "by_district" LIMIT 10;

 * sqlite:///./census/census.db?check_same_thread=false

[('Achham', 49962, 39368, 228907, 105390, 123517),
 ('Arghakhanchi', 49073, 45012, 176534, 80468, 96066),
 ('Baglung', 65334, 58445, 248964, 115864, 133100),
 ('Baitadi', 50472, 42288, 244400, 115426, 128974),
 ('Bajhang', 38368, 32916, 189023, 88918, 100105),
 ('Bajura', 28922, 23891, 138998, 67608, 71390),
 ('Banke', 131920, 110130, 601666, 293679, 307987),
 ('Bara', 134362, 112301, 742667, 379072, 363595),
 ('Bardiya', 106429, 98917, 458922, 216081, 242841),
 ('Bhaktapur', 108453, 70849, 425392, 213662, 211730)]

In [24]:
%%sql
CREATE VIEW "most_populated" AS
SELECT
    "district",
    SUM("families") AS "families",
    SUM("households") AS "households",
    SUM("population") AS "population",
    SUM("male") AS "male",
    SUM("female") AS "female"
FROM "census"
GROUP BY "district"
ORDER BY "population" DESC;

 * sqlite:///./census/census.db?check_same_thread=false

[]

In [25]:
%sql SELECT * FROM "most_populated";

 * sqlite:///./census/census.db?check_same_thread=false

[('Kathmandu', 537916, 275806, 1988606, 1001798, 986808),
 ('Morang', 274651, 241415, 1147186, 557527, 589659),
 ('Rupandehi', 241432, 195087, 1117667, 546297, 571370),
 ('Jhapa', 246138, 219989, 994090, 477496, 516594),
 ('Sunsari', 216874, 181777, 932452, 452087, 480365),
 ('Kailali', 200513, 183692, 907816, 436652, 471164),
 ('Dhanusa', 180826, 146470, 872713, 433812, 438901),
 ('Sarlahi', 168406, 138412, 856443, 432599, 423844),
 ('Rautahat', 139355, 111563, 821205, 412269, 408936),
 ('Siraha', 154593, 123536, 748416, 369049, 379367),
 ('Bara', 134362, 112301, 742667, 379072, 363595),
 ('Mahottari', 145900, 117494, 715040, 354952, 360088),
 ('Chitawan', 182041, 153629, 713750, 347173, 366577),
 ('Saptari', 151291, 124324, 711759, 354183, 357576),
 ('Kapilbastu', 122689, 103739, 684602, 335573, 349029),
 ('Dang', 165742, 149249, 673072, 318994, 354078),
 ('Parsa', 115149, 93719, 647319, 333274, 314045),
 ('Banke', 131920, 110130, 601666, 293679, 307987),
 ('Kaski', 163476, 120572, 594041, 287853, 306188),
 ('Lalitpur', 141006, 97388, 547624, 274846, 272778),
 ('Kanchanpur', 111899, 103371, 514790, 241037, 273753),
 ('Makwanpur', 106606, 96214, 461053, 228472, 232581),
 ('Bardiya', 106429, 98917, 458922, 216081, 242841),
 ('Bhaktapur', 108453, 70849, 425392, 213662, 211730),
 ('Surkhet', 99326, 87288, 413332, 198106, 215226),
 ('Nawalparasi West', 83878, 73259, 384454, 187072, 197382),
 ('Nawalparasi East', 95351, 84688, 380858, 179220, 201638),
 ('Kavrepalanchok', 93182, 83925, 363416, 177746, 185670),
 ('Udayapur', 81788, 75932, 342051, 164379, 177672),
 ('Tanahu', 93168, 81642, 326962, 152342, 174620),
 ('Dhading', 84463, 78663, 322751, 157207, 165544),
 ('Sindhuli', 69373, 64593, 297660, 145327, 152333),
 ('Ilam', 71558, 68327, 280498, 139518, 140980),
 ('Sindhupalchok', 72956, 69709, 261422, 128065, 133357),
 ('Nuwakot', 69150, 65724, 260920, 126999, 133921),
 ('Syangja', 70710, 62856, 254277, 117440, 136837),
 ('Dailekh', 55708, 48776, 253319, 121675, 131644),
 ('Gorkha', 72800, 68236, 251049, 118771, 132278),
 ('Baglung', 65334, 58445, 248964, 115864, 133100),
 ('Gulmi', 66721, 61218, 246558, 112517, 134041),
 ('Baitadi', 50472, 42288, 244400, 115426, 128974),
 ('Palpa', 64258, 56223, 239520, 109770, 129750),
 ('Salyan', 55400, 51984, 238668, 114953, 123715),
 ('Rolpa', 52989, 49587, 235031, 109834, 125197),
 ('Pyuthan', 56960, 52170, 230634, 103333, 127301),
 ('Achham', 49962, 39368, 228907, 105390, 123517),
 ('Doti', 46100, 36806, 205683, 95066, 110617),
 ('Jajarkot', 38054, 34309, 189365, 93795, 95570),
 ('Bajhang', 38368, 32916, 189023, 88918, 100105),
 ('Arghakhanchi', 49073, 45012, 176534, 80468, 96066),
 ('Khotang', 42104, 40392, 175340, 86521, 88819),
 ('Panchthar', 42968, 39406, 173273, 85971, 87302),
 ('Dolakha', 50653, 47847, 171676, 83122, 88554),
 ('Ramechhap', 46935, 45073, 170620, 80778, 89842),
 ('Rukum West', 37702, 34002, 165239, 80016, 85223),
 ('Bhojpur', 38920, 37401, 157817, 77362, 80455),
 ('Sankhuwasabha', 39300, 36682, 156457, 77473, 78984),
 ('Lamjung', 44873, 40101, 153480, 73209, 80271),
 ('Dhankuta', 37888, 35086, 149384, 72669, 76715),
 ('Kalikot', 26956, 22929, 144917, 72243, 72674),
 ('Okhaldhunga', 34689, 34111, 140914, 69322, 71592),
 ('Dadeldhura', 31608, 26503, 139420, 65930, 73490),
 ('Bajura', 28922, 23891, 138998, 67608, 71390),
 ('Darchula', 29186, 25200, 135056, 65349, 69707),
 ('Parbat', 37601, 33049, 132352, 62799, 69553),
 ('Taplejung', 28530, 26139, 120359, 60524, 59835),
 ('Jumla', 24496, 22400, 118393, 58913, 59480),
 ('Myagdi', 29201, 25352, 105367, 50694, 54673),
 ('Solukhumbu', 26402, 25388, 104768, 52629, 52139),
 ('Terhathum', 22022, 20352, 88885, 43563, 45322),
 ('Mugu', 12535, 11791, 66658, 33448, 33210),
 ('Rukum East', 13163, 11607, 57540, 28020, 29520),
 ('Humla', 11484, 10313, 55496, 27982, 27514),
 ('Rasuwa', 11841, 11362, 45554, 22859, 22695),
 ('Dolpa', 9429, 7995, 42959, 21276, 21683),
 ('Mustang', 3751, 3268, 14596, 8174, 6422),
 ('Manang', 1545, 1447, 4925, 2547, 2378)]