In [1]:
import sqlite3

In [2]:
conn = sqlite3.connect("./cyberchase.db")
conn.close()

In [3]:
%load_ext sql
%config SqlMagic.feedback=False
%sql sqlite:///cyberchase.db?check_same_thread=false
%sql SELECT name FROM sqlite_master WHERE type='table';

 * sqlite:///cyberchase.db?check_same_thread=false

[('episodes',)]

In [8]:
%sql SELECT * FROM "episodes" LIMIT 10;

 * sqlite:///cyberchase.db?check_same_thread=false

[(1, 1, 1, 'Lost My Marbles', 'Navigation', '2002-01-21', 'CYB001'),
 (2, 1, 2, 'Castleblanca', 'Data Collection and Analysis', '2002-01-22', 'CYB010'),
 (3, 1, 3, 'R-Fair City', 'Probability and chance', '2002-01-23', 'CYB004'),
 (4, 1, 4, 'Snow Day to be Exact', 'Estimation', '2002-01-24', 'CYB007'),
 (5, 1, 5, 'Sensible Flats', 'Area', '2002-01-25', 'CYB005'),
 (6, 1, 6, 'Zeus on the Loose', 'Fractions', '2002-01-28', 'CYB002'),
 (7, 1, 7, 'The Poddleville Case', 'Patterns', '2002-01-29', 'CYB006'),
 (8, 1, 8, 'And They Counted Happily Ever After', 'Number, Operations, and Counting', '2002-01-30', 'CYB003'),
 (9, 1, 9, 'Clock Like An Egyptian', 'Time Keeping', '2002-01-31', 'CYB009'),
 (10, 1, 10, 'Secrets of Symmetria', 'Symmetry', '2002-02-01', 'CYB008')]

## 01  
Write a SQL query to list the titles of all episodes in Cyberchase’s original season, Season 1.

In [47]:
%%sql
SELECT "title"
FROM "episodes"
WHERE "season" IS 1;

 * sqlite:///cyberchase.db?check_same_thread=false

[('Lost My Marbles',),
 ('Castleblanca',),
 ('R-Fair City',),
 ('Snow Day to be Exact',),
 ('Sensible Flats',),
 ('Zeus on the Loose',),
 ('The Poddleville Case',),
 ('And They Counted Happily Ever After',),
 ('Clock Like An Egyptian',),
 ('Secrets of Symmetria',),
 ('A Day at the Spa',),
 ('Of All The Luck',),
 ('Eureeka',),
 ('Cool It',),
 ('Find Those Gleamers',),
 ('Codename: Icky',),
 ('Return to Sensible Flats',),
 ('Problem Solving in Shangri-La',),
 ('Send in the Clones',),
 ('Trading Places',),
 ('Less Than Zero',),
 ('Model Behavior',),
 ('Fortress of Attitude',),
 ('Size Me Up',),
 ('A Battle of Equals',),
 ('Out of Sync',)]

## 02  
List the season number of, and title of, the first episode of every season.

In [9]:
%%sql
SELECT "season", "title"
FROM "episodes"
WHERE "episode_in_season" == 1;

 * sqlite:///cyberchase.db?check_same_thread=false

[(1, 'Lost My Marbles'),
 (2, 'Hugs & Witches'),
 (3, 'EcoHaven CSE'),
 (4, 'Balancing Act'),
 (5, 'The Halloween Howl'),
 (6, "Digit's B-Day Surprise"),
 (7, 'Weather Watchers Gone With The Fog'),
 (8, "The Hacker's Challenge"),
 (9, 'An Urchin Matter'),
 (10, 'Fit to be Heroes'),
 (11, 'Watts of Halloween Trouble'),
 (12, 'Space Waste Odyssey'),
 (13, 'Duck Stop'),
 (14, 'Clean-Up on Isle 8')]

## 03  
Find the production code for the episode “Hackerized!”.

In [12]:
%%sql
SELECT "production_code"
FROM "episodes"
WHERE "title" == 'Hackerized!';

 * sqlite:///cyberchase.db?check_same_thread=false

[('CYB091',)]

## 04  
Write a query to find the titles of episodes that do not yet have a listed topic.

In [13]:
%%sql
SELECT "title"
FROM "episodes"
WHERE "topic" IS NULL;

 * sqlite:///cyberchase.db?check_same_thread=false

[('Space Waste Odyssey',),
 ('Space Waste Odyssey',),
 ('Giving Thanks Day',),
 ('A Garden Grows in Botlyn',),
 ('Missing Bats in Sensible Flats',),
 ('Water Woes',),
 ('Soil Turmoil',),
 ('Hacker Hugs a Tree',),
 ('Pursuit of the Prism of Power',),
 ('Composting in the Clutch',),
 ('A Camping Conundrum',),
 ('Journey of a Thousand Food Miles',),
 ('Duck Stop',),
 ('The Great Outdoors',),
 ('Coral Grief',),
 ('Sustainable by Design',),
 ("Hacker's Bright Idea",),
 ('Buzz and the Tree',),
 ('The Lilting Loons',),
 ('Living in Disharmony',),
 ('Traffic Trouble',),
 ('A Garden is Born',),
 ('Clean-Up on Isle 8',),
 ('Weather or Not',),
 ('Weather or Not',),
 ('Trees, Please',)]

## 05  
Find the title of the holiday episode that aired on December 31st, 2004.

In [15]:
%%sql
SELECT "title"
FROM "episodes"
WHERE "air_date" IS '2004-12-31';

 * sqlite:///cyberchase.db?check_same_thread=false

[('Starlight Night',)]

## 06  
List the titles of episodes from season 6 (2008) that were released early, in 2007.

In [49]:
%%sql
SELECT "title"
FROM "episodes"
WHERE "air_date" LIKE '2007-%'
AND "season" IS 6;

 * sqlite:///cyberchase.db?check_same_thread=false

[("Digit's B-Day Surprise",), ('When Penguins Fly',)]

## 07  
Write a SQL query to list the titles and topics of all episodes teaching fractions.

In [22]:
%%sql
SELECT "title", "topic"
FROM "episodes"
WHERE "topic" LIKE '%fractions%';

 * sqlite:///cyberchase.db?check_same_thread=false

[('Zeus on the Loose', 'Fractions'),
 ('Harriet Hippo & the Mean Green', 'Equivalent Fractions'),
 ('Shari Spotter and the Cosmic Crumpets', 'Mixed-Number Fractions'),
 ('A Fraction of a Chance', 'Fractions 101'),
 ('Peace, Love, and Hackerness', 'Measuring with Mixed Number Fractions'),
 ('Trash Creep', 'Fractions, Effects of Trash, and Recycling')]

## 08  
Write a query that counts the number of episodes released in the last 6 years, from 2018 to 2023, inclusive.

In [24]:
%%sql
SELECT COUNT("title")
FROM "episodes"
WHERE "air_date"
BETWEEN '2018-01-01' AND '2023-12-31';

 * sqlite:///cyberchase.db?check_same_thread=false

[(31,)]

## 09  
Write a query that counts the number of episodes released in Cyberchase’s first 6 years, from 2002 to 2007, inclusive.

In [25]:
%%sql
SELECT COUNT("title")
FROM "episodes"
WHERE "air_date"
BETWEEN '2002-01-01' AND '2007-12-31';

 * sqlite:///cyberchase.db?check_same_thread=false

[(74,)]

## 10  
Write a SQL query to list the ids, titles, and production codes of all episodes. Order the results by production code, from earliest to latest.

In [27]:
%%sql
SELECT "id", "title", "production_code"
FROM "episodes"
ORDER BY "production_code" ASC;

 * sqlite:///cyberchase.db?check_same_thread=false

[(1, 'Lost My Marbles', 'CYB001'),
 (6, 'Zeus on the Loose', 'CYB002'),
 (8, 'And They Counted Happily Ever After', 'CYB003'),
 (3, 'R-Fair City', 'CYB004'),
 (5, 'Sensible Flats', 'CYB005'),
 (7, 'The Poddleville Case', 'CYB006'),
 (4, 'Snow Day to be Exact', 'CYB007'),
 (10, 'Secrets of Symmetria', 'CYB008'),
 (9, 'Clock Like An Egyptian', 'CYB009'),
 (2, 'Castleblanca', 'CYB010'),
 (11, 'A Day at the Spa', 'CYB011'),
 (17, 'Return to Sensible Flats', 'CYB012'),
 (21, 'Less Than Zero', 'CYB013'),
 (14, 'Cool It', 'CYB014'),
 (13, 'Eureeka', 'CYB015'),
 (18, 'Problem Solving in Shangri-La', 'CYB016'),
 (15, 'Find Those Gleamers', 'CYB017'),
 (12, 'Of All The Luck', 'CYB018'),
 (16, 'Codename: Icky', 'CYB019'),
 (19, 'Send in the Clones', 'CYB020'),
 (20, 'Trading Places', 'CYB021'),
 (26, 'Out of Sync', 'CYB022'),
 (22, 'Model Behavior', 'CYB023'),
 (23, 'Fortress of Attitude', 'CYB024'),
 (24, 'Size Me Up', 'CYB025'),
 (25, 'A Battle of Equals', 'CYB026'),
 (29, 'Harriet Hippo & the Mean Green', 'CYB027'),
 (30, 'True Colors', 'CYB028'),
 (27, 'Hugs & Witches', 'CYB029'),
 (28, 'Totally Rad', 'CYB030'),
 (31, 'All the Right Angles', 'CYB031'),
 (33, 'The Eye of Rom', 'CYB032'),
 (32, "Mother's Day", 'CYB033'),
 (40, 'Trick or Treat', 'CYB034'),
 (34, 'A Whale of a Tale', 'CYB035'),
 (35, 'Double Trouble', 'CYB036'),
 (36, 'Raising the Bar', 'CYB037'),
 (39, 'A Time to Cook', 'CYB038'),
 (38, 'The Guilty Party', 'CYB039'),
 (37, 'The Wedding Scammer', 'CYB040'),
 (42, 'The Borg of the Ring', 'CYB041'),
 (43, 'A World Without Zero', 'CYB042'),
 (41, 'EcoHaven CSE', 'CYB043'),
 (44, 'A Piece of the Action', 'CYB044'),
 (46, 'The Grapes of Plath', 'CYB045'),
 (45, 'The Creech Who Would be Crowned', 'CYB046'),
 (48, 'Be Reasonable', 'CYB047'),
 (51, 'Shari Spotter and the Cosmic Crumpets', 'CYB048'),
 (52, 'Starlight Night', 'CYB049'),
 (47, 'A Perfect Fit', 'CYB050'),
 (49, 'The Snelfu Snafu', 'CYB051'),
 (50, 'The Snelfu Snafu', 'CYB052'),
 (60, 'A Crinkle In Time', 'CYB053'),
 (54, 'The Icky Factor', 'CYB054'),
 (59, 'The Case of the Missing Memory', 'CYB055'),
 (53, 'Balancing Act', 'CYB056'),
 (55, 'Penguin Tears', 'CYB057'),
 (58, 'A Change of Art', 'CYB058'),
 (56, 'Past Perfect Prediction', 'CYB059'),
 (61, "A Broom Of One's Own", 'CYB060'),
 (57, 'Measure For Measure', 'CYB061'),
 (62, 'A Tikiville Turkey Day', 'CYB062'),
 (64, 'A Clean Sweep', 'CYB063'),
 (65, 'Designing Mr. Perfect', 'CYB064'),
 (68, 'The Flying Parallinis', 'CYB065'),
 (66, 'EcoHaven Ooze', 'CYB066'),
 (67, 'The Fairy Borg Father', 'CYB067'),
 (70, 'Inside Hacker', 'CYB068'),
 (71, 'On the Line', 'CYB069'),
 (72, 'A Fraction of a Chance', 'CYB070'),
 (63, 'The Halloween Howl', 'CYB071'),
 (69, 'Crystal Clear', 'CYB072'),
 (73, "Digit's B-Day Surprise", 'CYB073'),
 (74, 'When Penguins Fly', 'CYB074'),
 (75, 'Unhappily Ever After', 'CYB075'),
 (76, "Escape From Merlin's Maze", 'CYB076'),
 (77, 'Step By Step', 'CYB077'),
 (81, 'Chaos as Usual', 'CYB078'),
 (78, 'Team Spirit', 'CYB079'),
 (79, 'Jimaya Jam', 'CYB080'),
 (80, 'A Perfect Score', 'CYB081'),
 (82, 'Spheres of Fears', 'CYB082'),
 (83, 'Weather Watchers Gone With The Fog', 'CYB083'),
 (84, 'The Emperor Has Snow Clothes', 'CYB084'),
 (85, 'The X-Factor', 'CYB085'),
 (86, "Blowin' in the Wind Blowin in the Wind", 'CYB086'),
 (87, "Father's Day", 'CYB087'),
 (88, 'The Deedle Beast', 'CYB088'),
 (89, 'Spellbound', 'CYB089'),
 (90, "The Hacker's Challenge", 'CYB090'),
 (93, 'Hackerized!', 'CYB091'),
 (94, 'The Bluebird of Zappiness', 'CYB092'),
 (91, 'Face-Off!', 'CYB093'),
 (92, 'Peace, Love, and Hackerness', 'CYB094'),
 (95, 'An Urchin Matter', 'CYB095'),
 (96, 'Going Solar', 'CYB096'),
 (97, 'Trash Creep', 'CYB097'),
 (98, 'The Cyberchase Movie', 'CYB099'),
 (99, 'The Cyberchase Movie', 'CYB100'),
 (100, 'Fit to be Heroes', 'CYB101'),
 (101, 'A Recipe for Chaos', 'CYB102'),
 (102, 'A Seedy Business', 'CYB103'),
 (103, 'Parks and Recreation', 'CYB104'),
 (104, 'Bottled Up', 'CYB105'),
 (105, 'Watts of Halloween Trouble', 'CYB106'),
 (106, "Creech's Creature Quandary", 'CYB107'),
 (107, 'A Murky Mystery in Mermaidos', 'CYB108'),
 (108, 'Plantasaurus!', 'CYB109'),
 (109, 'A Reboot Eve to Remember', 'CYB110'),
 (110, 'Housewarming Party', 'CYB111'),
 (111, 'Invasion of the Funky Flower', 'CYB112'),
 (112, 'A Renewable Hope', 'CYB113'),
 (113, 'The Migration Situation', 'CYB114'),
 (114, "Back to Canalia's Future", 'CYB115'),
 (117, 'Giving Thanks Day', 'CYB116'),
 (116, 'Space Waste Odyssey', 'CYB117'),
 (115, 'Space Waste Odyssey', 'CYB118'),
 (118, 'A Garden Grows in Botlyn', 'CYB119'),
 (119, 'Missing Bats in Sensible Flats', 'CYB120'),
 (120, 'Water Woes', 'CYB121'),
 (121, 'Soil Turmoil', 'CYB122'),
 (122, 'Hacker Hugs a Tree', 'CYB123'),
 (123, 'Pursuit of the Prism of Power', 'CYB124'),
 (124, 'Composting in the Clutch', 'CYB125'),
 (125, 'A Camping Conundrum', 'CYB126'),
 (126, 'Journey of a Thousand Food Miles', 'CYB127'),
 (127, 'Duck Stop', 'CYB128'),
 (128, 'The Great Outdoors', 'CYB129'),
 (129, 'Coral Grief', 'CYB130'),
 (130, 'Sustainable by Design', 'CYB131'),
 (131, "Hacker's Bright Idea", 'CYB132'),
 (132, 'Buzz and the Tree', 'CYB133'),
 (133, 'The Lilting Loons', 'CYB134'),
 (134, 'Living in Disharmony', 'CYB135'),
 (135, 'Traffic Trouble', 'CYB136'),
 (136, 'A Garden is Born', 'CYB137'),
 (137, 'Clean-Up on Isle 8', 'CYB138'),
 (140, 'Trees, Please', 'CYB139'),
 (138, 'Weather or Not', 'CYB140'),
 (139, 'Weather or Not', 'CYB141')]

## 11  
List the titles of episodes from season 5, in reverse alphabetical order.

In [28]:
%%sql
SELECT "title"
FROM "episodes"
WHERE "season" IS '5'
ORDER BY "title" DESC;

 * sqlite:///cyberchase.db?check_same_thread=false

[('The Halloween Howl',),
 ('The Flying Parallinis',),
 ('The Fairy Borg Father',),
 ('On the Line',),
 ('Inside Hacker',),
 ('EcoHaven Ooze',),
 ('Designing Mr. Perfect',),
 ('Crystal Clear',),
 ('A Fraction of a Chance',),
 ('A Clean Sweep',)]

## 12  
Count the number of unique episode titles.

In [30]:
%%sql
SELECT COUNT(DISTINCT "title")
FROM "episodes";

 * sqlite:///cyberchase.db?check_same_thread=false

[(136,)]

## 13  
Write a SQL query to explore a question of your choice. This query should:
- Involve at least one condition, using `WHERE` with `AND` or `OR`

Question: Write a SQL query to retrieve the titles and topics of episodes published between 2002 and 2010 (inclusive) that are on the topic 'data'.

In [35]:
%%sql
SELECT "title"
FROM "episodes"
WHERE "air_date"
BETWEEN '2002-01-01' AND '2010-12-31'
AND "topic" LIKE '%data%';

 * sqlite:///cyberchase.db?check_same_thread=false

[('Castleblanca',),
 ('Hugs & Witches',),
 ('Past Perfect Prediction',),
 ('Chaos as Usual',),
 ('Hackerized!',)]

## Advanced (Optional)

Write a SQL query to find the titles of episodes that have aired during the holiday season, usually in December in the United States.
- Your query should output a table with a single column for the title of each episode.
- Try to find a better solution than `LIKE` if you can!

In [38]:
%%sql
SELECT "title"
FROM "episodes"
WHERE strftime('%m',"air_date")=='12';

 * sqlite:///cyberchase.db?check_same_thread=false

[('Starlight Night',),
 ('When Penguins Fly',),
 ("Creech's Creature Quandary",),
 ('A Murky Mystery in Mermaidos',),
 ('Plantasaurus!',),
 ('A Reboot Eve to Remember',)]

Write a SQL query to find, for each year, the first day of the year that PBS released a Cyberchase episode.
- Your query should output a table with two columns, one for the year and one for the earliest month and day an episode was released that year.

In [46]:
%%sql
SELECT
  strftime('%Y', "air_date") AS 'year',
  MIN(strftime('%m-%d', "air_date")) AS 'earliest_release'
FROM "episodes"
GROUP BY strftime('%Y', "air_date");

 * sqlite:///cyberchase.db?check_same_thread=false

[('2002', '01-21'),
 ('2003', '02-14'),
 ('2004', '05-03'),
 ('2005', '04-15'),
 ('2006', '10-31'),
 ('2007', '04-16'),
 ('2008', '02-19'),
 ('2009', '04-20'),
 ('2010', '06-25'),
 ('2013', '11-04'),
 ('2014', '04-21'),
 ('2015', '11-09'),
 ('2017', '10-23'),
 ('2018', '04-16'),
 ('2019', '04-19'),
 ('2020', '02-14'),
 ('2022', '02-25'),
 ('2023', '04-21')]